daemonize: false
plugins: nfprobe
#nfprobe_ifindex_in: 3
#nfprobe_ifindex_out: 3
#nfprobe_receiver: 192.168.1.183:2055
# nfprobe_receiver: nfacctd:2055
pcap_interface: enp0s8
#pre_tag_map: /etc/pmacct/pretag.map
nfprobe_ifindex: 3
nfprobe_direction: 3
nfprobe_receiver: 127.0.0.1:2055
aggregate: src_host, dst_host, src_port, dst_port, proto, in_iface, out_iface, peer_src_ip
nfprobe_timeouts: tcp=60:udp=60:general=60:maxlife=300
debug: false
