daemonize: false
#interface: enp0s8
plugins: sfprobe
sampling_rate: 1000
#sfprobe_receiver: 192.168.1.183:6343
#sfprobe_receiver: sfacctd:634
sfprobe_receiver: 127.0.0.1:6343
#sfprobe_version: 5
aggregate: src_host, dst_host, src_port, dst_port, proto, in_iface, out_iface, peer_src_ip
#snaplen: 128
