daemonize: false
debug: true

sfacctd_ip: 0.0.0.0
sfacctd_port: 6343

plugins: pgsql[in]

sql_host: timescaledb
sql_user: postgres
sql_passwd: postgres
sql_db: postgres
sql_table: sflow_data

sql_optimize_clauses: true

sql_refresh_time: 10

# Агрегация по стандартным ключам
aggregate: src_host, dst_host, src_port, dst_port, proto, in_iface, out_iface, peer_src_ip

sql_history: 1 
# 5s
sql_history_roundoff: m
sql_dont_try_update: true
# Для sFlow можно добавить sampling_rate, если нужно

aggregate_filter[in]: not (dst net 224.0.0.0/4 or dst host 255.255.255.255 or dst port 1900 or dst port 5353 or dst host 239.255.255.250 or dst host 224.0.0.251 or dst host 192.168.1.255 or dst port 15600)
