daemonize: false
debug: true

nfacctd_ip: 0.0.0.0
nfacctd_port: 2055

plugins: pgsql[in]

sql_host: timescaledb
sql_user: postgres
sql_passwd: postgres
sql_db: postgres
sql_table: netflow_data

sql_optimize_clauses: true

sql_refresh_time: 10

aggregate: src_host, dst_host, src_port, dst_port, proto, in_iface, out_iface, peer_src_ip

# для гипертаблицы timescaleDB
sql_history: 1m
sql_history_roundoff: m

nfacctd_netflow_version: 8

aggregate_filter[in]: not (dst net 224.0.0.0/4 or dst host 255.255.255.255 or dst port 1900 or dst port 5353 or dst host 239.255.255.250 or dst host 224.0.0.251 or dst host 192.168.1.255 or dst port 15600)
